baseurl = "/"
title = "Shan MH"
languageCode = "en-us"
paginate = "10" # Number of posts per page
theme = "mainroad"
#disqusShortname = "" # Enable comments by entering your Disqus shortname
#googleAnalytics = "" # Enable Google Analytics by entering your tracking id

[[menu.main]]
    name = "About"
    url = "/about.html"
#[[menu.main]]
#    name = "GitHub"
#    url = ""

[Author]
    name = "Shan MH"
    bio = "John Doe's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
    avatar = "img/avatar.png"


[Params]
    subtitle = "I hear and I forget. I see and I remember. I do and I understand." # Subtitle of your site
    description = "" # Description of your site
    opengraph = true
    readmore = false # Show "Read more" button in list if true
    leftsidebar = false # Move sidebar to the left side if true
    authorbox = false
    post_navigation = true
    postSections = ["post"]


[Params.widgets]
    search = false # Enable "Search" widget
    recent_articles = true # Enable "Recent arcticles" widget
    categories = true # Enable "Categories" widget
    tags = false # Enable "Tags" widget
        tags_counter = false # Enable counter for each tag in "Tags" widget (disabled by default)